### ISSUE TITLE
Remove Jackson warning when starting the UC server locally

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#104]
When I start the UC server locally with `bin/start-uc-server`, I get a Jackson warning, see the following screenshot:

<img width="1183" alt="Screenshot 2024-06-28 at 8 33 23 AM" src="https://github.com/unitycatalog/unitycatalog/assets/2722395/39b62f90-7d7e-4361-92fd-bccb9f98ec13">

Would be nice if there wasn't any warning.

**Comment by vikrantpuppala** [comment]
I think you might've not updated to the latest main? We merged #94 yesterday that should've resolved this.

**Comment by MrPowers** [comment]
@vikrantpuppala - I am up to date with the latest main commit and still seeing this.

**Comment by vikrantpuppala** [comment]
Are you sure about this? I see another issue, the art in the image above has "vv0.1.0-SNAPSHOT" which was also fixed to "v0.1.0-SNAPSHOT"

**Comment by filipovskid** [comment]
I am unable to reproduce the issue, there are no warnings on 6c2a9c3. I did reproduce it on 474d676 before the fix was applied with #94. 

Please go to the latest commit and run the following:
```console
$ build/sbt clean
$ bin/start-uc-server
```
If you ran the server on an older version you might still be using stale jars. `bin/start-uc-server` uses the existing jars if the project has already been compiled.

**Comment by MrPowers** [comment]
<img width="960" alt="Screenshot 2024-06-28 at 12 31 29 PM" src="https://github.com/unitycatalog/unitycatalog/assets/2722395/26dadb70-f945-4cbd-b728-5638c4380513">

Thanks @filipovskid - that worked!
